<?php
use Dompdf\Dompdf;
use Dompdf\Options;

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../models/ReferralModel.php';
require_once __DIR__ . '/../models/PatientModel.php';

class PDFHelper {

  public static function generateReferralPDF($referralId) {
    $ref = ReferralModel::getById($referralId);
    if (!$ref) exit('Referral not found');

    $patient = PatientModel::getById($ref['patient_id']);
    if (!$patient) exit('Patient not found');

    $html = self::renderReferralHTML($ref, $patient);

    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $filename = 'Referral_' . ($ref['referral_code'] ?? $referralId) . '.pdf';
    $dompdf->stream($filename, ['Attachment' => false]);
    exit;
  }

  private static function renderReferralHTML($ref, $patient) {

    $safe = function($x){ return htmlspecialchars($x ?? '', ENT_QUOTES, 'UTF-8'); };

    return "
<html>
<head>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <style>
    body {
      font-family: DejaVu Sans, Arial, sans-serif;
      font-size: 12px;
      color: #111;
      line-height:1.4;
    }
    .container {
      width: 100%;
      position: relative;
      min-height: 100vh;
    }
    .header {
      text-align:center;
      font-size:18px;
      margin-bottom:15px;
      font-weight:bold;
      text-transform:uppercase;
    }
    table {
      width:100%;
      border-collapse:collapse;
      margin-bottom:12px;
    }
    th, td {
      border:1px solid #444;
      padding:6px;
      font-size:12px;
      text-align:left;
      vertical-align:top;
    }
    th {
      background:#f2f2f2;
      font-weight:bold;
    }
    .footer-note {
      position: absolute;
      bottom: 10px;
      width: 100%;
      text-align: center;
      font-size: 10px;
      color: #666;
      border-top:1px solid #ccc;
      padding-top:6px;
    }
  </style>
</head>
<body>
  <div class='container'>
    <div class='header'>Form 7 — TB Referral / Return Slip</div>

    <table>
      <tr><th>Referral Code</th><th>Referral Date</th></tr>
      <tr>
        <td>{$safe($ref['referral_code'])}</td>
        <td>{$safe(substr($ref['referral_date'] ?? '', 0, 10))}</td>
      </tr>
    </table>

    <table>
      <tr><th>Patient Code</th><th>Patient Name</th><th>TB Case #</th><th>Barangay</th></tr>
      <tr>
        <td>{$safe($patient['patient_code'])}</td>
        <td>{$safe($patient['name'] ?? '')}</td>
        <td>{$safe($patient['tb_case_number'])}</td>
        <td>{$safe($patient['barangay'] ?? $ref['patient_barangay'])}</td>
      </tr>
    </table>

    <table>
      <tr><th colspan='4'>Referring (Sender)</th></tr>
      <tr>
        <td><strong>Unit / Barangay</strong><br>{$safe($ref['referring_unit'])}</td>
        <td><strong>Tel</strong><br>{$safe($ref['referring_tel'])}</td>
        <td><strong>Email</strong><br>{$safe($ref['referring_email'])}</td>
        <td><strong>Address</strong><br>{$safe($ref['referring_address'])}</td>
      </tr>
    </table>

    <table>
      <tr><th>Reason for Referral</th></tr>
      <tr><td><pre>{$safe($ref['reason_for_referral'])}</pre></td></tr>
      <tr><th>Details / Clinical Summary</th></tr>
      <tr><td style='min-height:80px;'><pre>{$safe($ref['details'])}</pre></td></tr>
    </table>

    <table>
      <tr><th colspan='4'>Receiving (to be filled by receiving unit)</th></tr>
      <tr>
        <td><strong>Barangay</strong><br>{$safe($ref['receiving_barangay'])}</td>
        <td><strong>Unit</strong><br>{$safe($ref['receiving_unit'])}</td>
        <td><strong>Officer</strong><br>{$safe($ref['receiving_officer'])}</td>
        <td><strong>Date Received</strong><br>{$safe(substr($ref['date_received'] ?? '', 0, 10))}</td>
      </tr>
    </table>

    <table>
      <tr><th>Action Taken</th></tr>
      <tr><td style='min-height:60px;'><pre>{$safe($ref['action_taken'])}</pre></td></tr>
      <tr><th>Remarks</th></tr>
      <tr><td style='min-height:80px;'><pre>{$safe($ref['remarks'])}</pre></td></tr>
    </table>

    <div class='footer-note'>
      Generated by TB-MAS — This document is for clinical communication.<br>
      If printed, retain a copy for patient record.
    </div>
  </div>
</body>
</html>";
  }

}
