<?php
use Dompdf\Dompdf;
use Dompdf\Options;

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../models/ReferralModel.php';
require_once __DIR__ . '/../models/PatientModel.php';

class PDFHelper {

  public static function generateReferralPDF($referralId) {
    $ref = ReferralModel::getById($referralId);
    if (!$ref) exit('Referral not found');

    $patient = PatientModel::getById($ref['patient_id']);
    if (!$patient) exit('Patient not found');

    $html = self::renderReferralHTML($ref, $patient);

    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $filename = 'Referral_' . ($ref['referral_code'] ?? $referralId) . '.pdf';
    $dompdf->stream($filename, ['Attachment' => false]);
    exit;
  }

  private static function renderReferralHTML($ref, $patient) {

    $safe = function($x){ return htmlspecialchars($x ?? '', ENT_QUOTES, 'UTF-8'); };

    // Simple two-column/boxed layout to capture key form 7 fields.
    return "
    <html>
    <head>
      <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
      <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111; }
        .container { width: 100%; }
        .header { text-align:center; font-size:16px; margin-bottom:10px; font-weight:bold; }
        .section { border:1px solid #222; padding:10px; margin-bottom:10px; }
        .label { font-weight:bold; display:block; margin-bottom:4px; }
        .two { display:flex; gap:12px; }
        .col { flex:1; }
        .small { font-size:11px; color:#333; }
        .footer-note { font-size:10px; color:#666; margin-top:8px; }
        pre { white-space:pre-wrap; font-family: inherit; }
      </style>
    </head>
    <body>
      <div class='container'>
        <div class='header'>FORM 7 — TB Referral / Return Slip</div>

        <div class='section'>
          <div class='two'>
            <div class='col'>
              <div class='label'>Referral Code</div>
              <div class='small'>". $safe($ref['referral_code']) ."</div>
            </div>
            <div class='col'>
              <div class='label'>Referral Date</div>
              <div class='small'>". $safe(substr($ref['referral_date'] ?? '', 0, 10)) ."</div>
            </div>
          </div>

          <div style='margin-top:8px'>
            <div class='label'>Patient</div>
            <div class='small'>
              <strong>Patient code:</strong> ". $safe($patient['patient_code']) ."<br>
              <strong>TB case #:</strong> ". $safe($patient['tb_case_number']) ."<br>
              <strong>Barangay:</strong> ". $safe($patient['barangay'] ?? $ref['patient_barangay']) ."
            </div>
          </div>
        </div>

        <div class='section'>
          <div class='label'>Referring (Sender)</div>
          <div class='small'>
            <strong>Unit / Barangay:</strong> ". $safe($ref['referring_unit']) ."<br>
            <strong>Contact (Tel):</strong> ". $safe($ref['referring_tel']) ."<br>
            <strong>Email:</strong> ". $safe($ref['referring_email']) ."<br>
            <strong>Address:</strong> ". $safe($ref['referring_address']) ."
          </div>
        </div>

        <div class='section'>
          <div class='label'>Reason for Referral</div>
          <div class='small'><pre>". $safe($ref['reason_for_referral']) ."</pre></div>

          <div class='label' style='margin-top:8px'>Details / Clinical Summary</div>
          <div class='small'><pre>". $safe($ref['details']) ."</pre></div>
        </div>

        <div class='section'>
          <div class='label'>Receiving (to be filled by receiving unit)</div>
          <div class='small'>
            <strong>Receiving Barangay:</strong> ". $safe($ref['receiving_barangay']) ."<br>
            <strong>Receiving Unit:</strong> ". $safe($ref['receiving_unit']) ."<br>
            <strong>Receiving Officer:</strong> ". $safe($ref['receiving_officer']) ."<br>
            <strong>Date Received:</strong> ". $safe(substr($ref['date_received'] ?? '', 0, 10)) ."
          </div>

          <div style='margin-top:8px'>
            <div class='label'>Action Taken</div>
            <div class='small'><pre>". $safe($ref['action_taken']) ."</pre></div>
          </div>

          <div style='margin-top:8px'>
            <div class='label'>Remarks</div>
            <div class='small'><pre>". $safe($ref['remarks']) ."</pre></div>
          </div>
        </div>

        <div class='footer-note'>
          Generated by TB-MAS — This document is for clinical communication. If printed, retain a copy for patient record.
        </div>
      </div>
    </body>
    </html>
    ";
  }
  public static function generateContactsPDF($patient_id) {
    require_once __DIR__ . '/../models/ContactModel.php';
    require_once __DIR__ . '/../models/PatientModel.php';

    $patient = PatientModel::getById($patient_id);
    if (!$patient) exit('Patient not found');

    $contacts = ContactModel::getByPatient($patient_id);

    $html = self::renderContactsHTML($patient, $contacts);

    $options = new \Dompdf\Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new \Dompdf\Dompdf($options);

    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $dompdf->stream('Contacts_'.$patient['patient_code'].'.pdf', ['Attachment' => false]);
    exit;
}

private static function renderContactsHTML($patient, $contacts) {
    $safe = fn($x) => htmlspecialchars($x ?? '', ENT_QUOTES, 'UTF-8');

    $rows = "";
    foreach ($contacts as $c) {
        $rows .= "
          <tr>
            <td>{$safe($c['name'])}</td>
            <td>{$safe($c['age'])}</td>
            <td>{$safe($c['contact_number'])}</td>
            <td>{$safe($c['address'])}</td>
          </tr>
        ";
    }

    if (!$rows) {
        $rows = "<tr><td colspan='4' style='text-align:center;color:#777;'>No contacts recorded.</td></tr>";
    }

    return "
    <html>
    <head>
      <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size:12px; }
        table { width:100%; border-collapse:collapse; margin-top:10px; }
        th, td { border:1px solid #444; padding:6px; }
        th { background:#eee; }
        .header { text-align:center; font-size:18px; margin-bottom:15px; }
        .sub { font-size:13px; margin-bottom:8px; }
      </style>
    </head>
    <body>
      <div class='header'>Close Contacts — TB-MAS Records</div>

      <div class='sub'><strong>Patient:</strong> {$safe($patient['patient_code'])}</div>
      <div class='sub'><strong>TB Case #:</strong> {$safe($patient['tb_case_number'])}</div>
      <div class='sub'><strong>Barangay:</strong> {$safe($patient['barangay'])}</div>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Contact #</th>
            <th>Address</th>
          </tr>
        </thead>
        <tbody>
          $rows
        </tbody>
      </table>

    </body>
    </html>";
  }
}
?>
